/* Administration app */

/* Initial data */

-- Insert LanguageRelations

DO
$BODY$
DECLARE _id character varying(50); _us character varying(50); _gb character varying(50); _fr character varying(50); _es character varying(50); _ar character varying(50);

BEGIN
	SELECT "ID" INTO _us FROM public."cl_Languages" WHERE "Label" = 'US';
	SELECT "ID" INTO _gb FROM public."cl_Languages" WHERE "Label" = 'GB';
	SELECT "ID" INTO _fr FROM public."cl_Languages" WHERE "Label" = 'FR';
	SELECT "ID" INTO _es FROM public."cl_Languages" WHERE "Label" = 'ES';
	SELECT "ID" INTO _ar FROM public."cl_Languages" WHERE "Label" = 'AR';
	
	-- Languages
	
	SELECT "ID" INTO _id FROM public."cl_Languages" WHERE "Label" = 'US';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'en-US');
	SELECT "ID" INTO _id FROM public."cl_Languages" WHERE "Label" = 'GB';
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'en-GB');
	SELECT "ID" INTO _id FROM public."cl_Languages" WHERE "Label" = 'FR';
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'fr-FR');
	SELECT "ID" INTO _id FROM public."cl_Languages" WHERE "Label" = 'ES';
	CALL public."p_InsertLanguageRelation"(_es, _id, 'es-ES');
	SELECT "ID" INTO _id FROM public."cl_Languages" WHERE "Label" = 'AR';
	CALL public."p_InsertLanguageRelation"(_ar, _id, 'ar-SA');
	
	-- Continents
	
	SELECT "ID" INTO _id FROM public."cl_Continents" WHERE "Name" = 'Africa';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Africa');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Africa');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Afrique');
	SELECT "ID" INTO _id FROM public."cl_Continents" WHERE "Name" = 'America';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'America');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'America');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Amérique');
	SELECT "ID" INTO _id FROM public."cl_Continents" WHERE "Name" = 'Asia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Asia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Asia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Asie');
	SELECT "ID" INTO _id FROM public."cl_Continents" WHERE "Name" = 'Europe';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Europe');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Europe');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Europe');
	SELECT "ID" INTO _id FROM public."cl_Continents" WHERE "Name" = 'Oceania';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Oceania');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Oceania');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Oceanie');
	
	-- Countries
	
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Afghanistan';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Afghanistan');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Afghanistan');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Afghanistan');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Albania';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Albania');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Albania');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Albanie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Algeria';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Algeria');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Algeria');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Algérie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Åland Islands';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Åland Islands');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Åland Islands');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Les Iles Åland');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'American Samoa';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'American Samoa');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'American Samoa');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Samoa Américaines');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Andorra';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Andorra');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Andorra');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Andorres');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Angola';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Angola');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Angola');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Angola');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Anguilla';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Anguilla');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Anguilla');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Anguilla');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Antigua and Barbuda';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Antigua and Barbuda');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Antigua and Barbuda');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Antigua et Barbuda');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Argentina';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Argentina');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Argentina');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Argentine');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Armenia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Armenia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Armenia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Arménie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Aruba';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Aruba');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Aruba');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Aruba');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Australia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Australia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Australia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Australie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Austria';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Austria');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Austria');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Autriche');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Azerbaijan';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Azerbaijan');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Azerbaijan');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Azerbaijan');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Bahamas';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Bahamas');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Bahamas');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Bahamas');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Bahrain';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Bahrain');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Bahrain');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Bahrein');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Bangladesh';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Bangladesh');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Bangladesh');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Bangladesh');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Barbados';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Barbados');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Barbados');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Barbades');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Belarus';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Belarus');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Belarus');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Biélorussie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Belgium';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Belgium');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Belgium');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Belgique');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Belize';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Belize');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Belize');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Bélize');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Benin';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Benin');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Benin');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Bénin');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Bermuda';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Bermuda');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Bermuda');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Bermudes');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Bhutan';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Bhutan');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Bhutan');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Bhoutan');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Bolivia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Bolivia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Bolivia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Bolivie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Bosnia and Herzegovina';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Bosnia and Herzegovina');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Bosnia and Herzegovina');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Bosnie Herzégovine');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Botswana';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Botswana');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Botswana');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Botswana');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Brazil';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Brazil');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Brazil');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Brésil');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'British Indian Ocean Territory';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'British Indian Ocean Territory');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'British Indian Ocean Territory');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Territoire britannique de l''océan Indien');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'British Virgin Islands';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'British Virgin Islands');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'British Virgin Islands');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Îles Vierges britanniques');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Brunei';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Brunei');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Brunei');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Brunei');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Bulgaria';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Bulgaria');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Bulgaria');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Bulgarie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Burkina Faso';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Burkina Faso');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Burkina Faso');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Burkina Faso');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Burundi';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Burundi');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Burundi');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Burundi');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Cambodia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Cambodia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Cambodia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Cambodge');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Cameroon';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Cameroon');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Cameroon');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Cameroun');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Canada';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Canada');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Canada');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Canada');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Cape Verde';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Cape Verde');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Cape Verde');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Cap Vert');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Caribbean Netherlands';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Caribbean Netherlands');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Caribbean Netherlands');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Pays-Bas caribéens');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Cayman Islands';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Cayman Islands');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Cayman Islands');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Îles Caïmans');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Central African Republic';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Central African Republic');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Central African Republic');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'République Centrafricaine');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Chad';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Chad');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Chad');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Tchad');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Chile';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Chile');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Chile');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Chili');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'China';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'China');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'China');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Chine');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Christmas Island';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Christmas Island');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Christmas Island');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Ile Christmas');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Cocos Islands';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Cocos Islands');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Cocos Islands');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Îles Cocos');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Colombia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Colombia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Colombia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Colombie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Comoros';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Comoros');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Comoros');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Comores');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Cook Islands';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Cook Islands');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Cook Islands');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Iles Cook');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Costa Rica';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Costa Rica');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Costa Rica');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Costa Rica');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Croatia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Croatia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Croatia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Croatie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Cuba';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Cuba');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Cuba');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Cuba');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Curacao';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Curacao');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Curacao');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Curacao');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Cyprus';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Cyprus');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Cyprus');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Chypre');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Czech Republic';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Czech Republic');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Czech Republic');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'République Tchèque');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Democratic Republic of the Congo';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Democratic Republic of the Congo');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Democratic Republic of the Congo');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'République Démocratique du Congo');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Denmark';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Denmark');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Denmark');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Danemark');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Djibouti';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Djibouti');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Djibouti');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Djibouti');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Dominica';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Dominica');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Dominica');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Dominique');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Dominican Republic';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Dominican Republic');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Dominican Republic');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'République Dominicaine');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'East Timor';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'East Timor');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'East Timor');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Timor Oriental');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Ecuador';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Ecuador');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Ecuador');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Equateur');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Egypt';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Egypt');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Egypt');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Egypte');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'El Salvador';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'El Salvador');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'El Salvador');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Le Salvador');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Equatorial Guinea';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Equatorial Guinea');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Equatorial Guinea');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Guinée Équatoriale');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Eritrea';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Eritrea');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Eritrea');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Érythrée');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Estonia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Estonia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Estonia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Estonie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Ethiopia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Ethiopia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Ethiopia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Ethiopie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Falkland Islands';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Falkland Islands');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Falkland Islands');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Iles Falkland');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Faroe Islands';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Faroe Islands');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Faroe Islands');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Îles Féroé');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Fiji';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Fiji');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Fiji');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Fiji');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Finland';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Finland');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Finland');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Finlande');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'France';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'France');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'France');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'France');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'French Guiana';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'French Guiana');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'French Guiana');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Guyane Française');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'French Polynesia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'French Polynesia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'French Polynesia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Polynésie française');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Gabon';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Gabon');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Gabon');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Gabon');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Gambia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Gambia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Gambia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Gambie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Georgia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Georgia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Georgia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Géorgie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Germany';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Germany');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Germany');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Allemagne');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Ghana';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Ghana');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Ghana');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Ghana');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Gibraltar';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Gibraltar');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Gibraltar');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Gibraltar');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Greece';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Greece');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Greece');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Grèce');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Greenland';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Greenland');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Greenland');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Groenland');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Grenada';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Grenada');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Grenada');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Grenade');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Guadeloupe';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Guadeloupe');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Guadeloupe');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Guadeloupe');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Guam';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Guam');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Guam');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Guam');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Guatemala';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Guatemala');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Guatemala');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Guatemala');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Guernsey';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Guernsey');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Guernsey');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Guernesey');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Guinea';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Guinea');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Guinea');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Guinée');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Guinea-Bissau';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Guinea-Bissau');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Guinea-Bissau');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Guinée-Bissau');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Guyana';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Guyana');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Guyana');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Guyane');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Haiti';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Haiti');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Haiti');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Haiti');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Honduras';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Honduras');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Honduras');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Honduras');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Hong Kong';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Hong Kong');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Hong Kong');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Hong Kong');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Hungary';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Hungary');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Hungary');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Hongrie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Iceland';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Iceland');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Iceland');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Islande');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'India';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'India');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'India');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Indie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Indonesia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Indonesia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Indonesia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Indonésie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Iran';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Iran');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Iran');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Iran');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Iraq';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Iraq');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Iraq');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Iraq');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Ireland';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Ireland');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Ireland');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Irelande');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Isle of Man';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Isle of Man');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Isle of Man');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'île de Man');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Israel';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Israel');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Israel');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Israël');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Italy';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Italy');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Italy');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Italie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Ivory Coast';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Ivory Coast');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Ivory Coast');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Côte d''Ivoire');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Jamaica';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Jamaica');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Jamaica');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Jamaique');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Japan';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Japan');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Japan');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Japan');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Jersey';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Jersey');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Jersey');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Jersey');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Jordan';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Jordan');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Jordan');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Jordanie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Kazakhstan';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Kazakhstan');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Kazakhstan');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Kazakhstan');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Kenya';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Kenya');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Kenya');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Kenya');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Kiribati';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Kiribati');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Kiribati');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Kiribati');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Kosovo';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Kosovo');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Kosovo');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Kosovo');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Kuwait';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Kuwait');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Kuwait');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Koweit');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Kyrgyzstan';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Kyrgyzstan');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Kyrgyzstan');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Kirghizistan');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Laos';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Laos');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Laos');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Laos');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Latvia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Latvia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Latvia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Lettonie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Lebanon';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Lebanon');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Lebanon');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Liban');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Lesotho';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Lesotho');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Lesotho');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Lesotho');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Liberia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Liberia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Liberia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Libéria');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Libya';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Libya');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Libya');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Libye');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Liechtenstein';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Liechtenstein');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Liechtenstein');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Liechtenstein');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Lithuania';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Lithuania');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Lithuania');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Lithuanie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Luxembourg';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Luxembourg');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Luxembourg');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Luxembourg');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Macau';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Macau');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Macau');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Macau');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Macedonia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Macedonia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Macedonia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Macédoine');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Madagascar';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Madagascar');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Madagascar');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Madagascar');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Malawi';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Malawi');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Malawi');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Malawi');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Malaysia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Malaysia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Malaysia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Malaisie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Maldives';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Maldives');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Maldives');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Maldives');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Mali';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Mali');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Mali');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Mali');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Malta';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Malta');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Malta');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Malte');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Marshall Islands';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Marshall Islands');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Marshall Islands');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Iles Marshall');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Martinique';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Martinique');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Martinique');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Martinique');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Mauritania';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Mauritania');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Mauritania');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Mauritanie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Mauritius';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Mauritius');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Mauritius');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Ile Maurice');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Mayotte';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Mayotte');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Mayotte');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Mayotte');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Mexico';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Mexico');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Mexico');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Mexique');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Micronesia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Micronesia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Micronesia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Micronésie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Moldova';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Moldova');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Moldova');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Moldavie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Monaco';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Monaco');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Monaco');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Monaco');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Mongolia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Mongolia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Mongolia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Mongolie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Montenegro';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Montenegro');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Montenegro');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Monténégro');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Montserrat';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Montserrat');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Montserrat');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Montserrat');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Morocco';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Morocco');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Morocco');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Maroc');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Mozambique';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Mozambique');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Mozambique');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Mozambique');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Myanmar';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Myanmar');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Myanmar');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Myanmar');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Namibia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Namibia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Namibia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Namibie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Nauru';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Nauru');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Nauru');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Nauru');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Nepal';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Nepal');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Nepal');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Népal');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Netherlands';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Netherlands');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Netherlands');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Pays-Bas');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'New Caledonia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'New Caledonia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'New Caledonia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Nouvelle Calédonie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'New Zealand';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'New Zealand');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'New Zealand');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Nouvelle-Zélande');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Nicaragua';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Nicaragua');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Nicaragua');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Nicaragua');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Niger';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Niger');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Niger');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Niger');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Nigeria';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Nigeria');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Nigeria');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Nigéria');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Niue';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Niue');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Niue');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Niué');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Norfolk Island';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Norfolk Island');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Norfolk Island');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Ile Norfolk');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'North Korea';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'North Korea');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'North Korea');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Corée du Nord');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Northern Mariana Islands';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Northern Mariana Islands');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Northern Mariana Islands');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Îles Mariannes du Nord');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Norway';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Norway');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Norway');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Norvège');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Oman';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Oman');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Oman');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Oman');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Pakistan';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Pakistan');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Pakistan');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Pakistan');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Palau';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Palau');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Palau');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Palau');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Palestine';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Palestine');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Palestine');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Palestine');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Panama';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Panama');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Panama');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Panama');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Papua New Guinea';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Papua New Guinea');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Papua New Guinea');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Papouasie Nouvelle Guinée');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Paraguay';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Paraguay');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Paraguay');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Paraguay');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Peru';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Peru');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Peru');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Peru');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Philippines';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Philippines');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Philippines');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Philippines');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Pitcairn';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Pitcairn');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Pitcairn');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Pitcairn');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Poland';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Poland');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Poland');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Pologne');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Portugal';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Portugal');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Portugal');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Portugal');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Puerto Rico';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Puerto Rico');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Puerto Rico');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Porto Rico');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Qatar';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Qatar');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Qatar');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Qatar');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Republic of the Congo';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Republic of the Congo');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Republic of the Congo');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'République du Congo');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Reunion';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Reunion');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Reunion');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Réunion');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Romania';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Romania');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Romania');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Roumanie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Russia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Russia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Russia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Russie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Rwanda';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Rwanda');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Rwanda');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Rwanda');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Saint Barthelemy';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Saint Barthelemy');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Saint Barthelemy');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Saint Barthélemy');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Saint Helena';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Saint Helena');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Saint Helena');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Sainte Hélène');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Saint Kitts and Nevis';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Saint Kitts and Nevis');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Saint Kitts and Nevis');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Saint-Christophe-et-Niévès');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Saint Lucia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Saint Lucia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Saint Lucia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Sainte Lucie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Saint Martin';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Saint Martin');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Saint Martin');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Saint Martin');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Saint Pierre and Miquelon';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Saint Pierre and Miquelon');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Saint Pierre and Miquelon');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Saint Pierre et Miquélon');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Saint Vincent and the Grenadines';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Saint Vincent and the Grenadines');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Saint Vincent and the Grenadines');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Saint Vincent et les Grenadines');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Samoa';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Samoa');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Samoa');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Samoa');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'San Marino';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'San Marino');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'San Marino');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Saint Marin');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Sao Tome and Principe';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Sao Tome and Principe');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Sao Tome and Principe');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Sao Tomé et Principe');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Saudi Arabia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Saudi Arabia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Saudi Arabia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Arabie Saoudite');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Senegal';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Senegal');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Senegal');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Sénégal');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Serbia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Serbia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Serbia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Serbie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Seychelles';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Seychelles');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Seychelles');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Seychelles');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Sierra Leone';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Sierra Leone');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Sierra Leone');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Sierra Leone');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Singapore';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Singapore');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Singapore');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Singapour');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Sint Maarten';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Sint Maarten');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Sint Maarten');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Saint-Martin');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Slovakia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Slovakia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Slovakia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Slovaquie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Slovenia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Slovenia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Slovenia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Slovénie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Solomon Islands';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Solomon Islands');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Solomon Islands');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Les îles Salomon');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Somalia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Somalia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Somalia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Somalie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'South Africa';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'South Africa');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'South Africa');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Afrique du Sud');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'South Korea';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'South Korea');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'South Korea');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Corée du Sud');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'South Sudan';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'South Sudan');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'South Sudan');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Soudan du sud');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Spain';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Spain');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Spain');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Espagne');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Sri Lanka';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Sri Lanka');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Sri Lanka');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Sri Lanka');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Sudan';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Sudan');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Sudan');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Soudan');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Suriname';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Suriname');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Suriname');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Suriname');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Svalbard and Jan Mayen';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Svalbard and Jan Mayen');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Svalbard and Jan Mayen');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Svalbard et Jan Mayen');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Swaziland';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Swaziland');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Swaziland');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Swaziland');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Sweden';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Sweden');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Sweden');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Suède');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Switzerland';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Switzerland');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Switzerland');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Suisse');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Syria';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Syria');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Syria');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Syrie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Taiwan';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Taiwan');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Taiwan');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Taiwan');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Tajikistan';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Tajikistan');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Tajikistan');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Tajikistan');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Tanzania';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Tanzania');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Tanzania');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Tanzanie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Thailand';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Thailand');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Thailand');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Thaïlande');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Togo';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Togo');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Togo');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Togo');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Tokelau';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Tokelau');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Tokelau');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Tokélaou');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Tonga';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Tonga');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Tonga');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Tonga');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Trinidad and Tobago';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Trinidad and Tobago');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Trinidad and Tobago');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Trinité-et-Tobago');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Tunisia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Tunisia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Tunisia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Tunisie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Turkey';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Turkey');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Turkey');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Turquie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Turkmenistan';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Turkmenistan');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Turkmenistan');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Turkmenistan');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Turks and Caicos Islands';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Turks and Caicos Islands');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Turks and Caicos Islands');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'îles Turques-et-Caïques');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Tuvalu';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Tuvalu');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Tuvalu');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Tuvalu');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'U.S. Virgin Islands';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'U.S. Virgin Islands');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'U.S. Virgin Islands');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Îles Vierges Américaines');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Uganda';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Uganda');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Uganda');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Ouganda');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Ukraine';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Ukraine');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Ukraine');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Ukraine');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'United Arab Emirates';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'United Arab Emirates');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'United Arab Emirates');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Emirats Arabes Unis');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'United Kingdom';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'United Kingdom');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'United Kingdom');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Royaume-Uni');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'United States';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'United States');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'United States');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'États-Unis');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Uruguay';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Uruguay');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Uruguay');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Uruguay');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Uzbekistan';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Uzbekistan');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Uzbekistan');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Uzbekistan');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Vanuatu';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Vanuatu');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Vanuatu');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Vanuatu');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Vatican';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Vatican');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Vatican');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Vatican');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Venezuela';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Venezuela');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Venezuela');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Vénézuéla');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Vietnam';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Vietnam');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Vietnam');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Vietnam');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Wallis and Futuna';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Wallis and Futuna');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Wallis and Futuna');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Wallis et Futuna');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Western Sahara';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Western Sahara');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Western Sahara');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Sahara Occidental');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Yemen';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Yemen');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Yemen');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Yémen');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Zambia';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Zambia');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Zambia');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Zambie');
	SELECT "ID" INTO _id FROM public."cl_Countries" WHERE "Name" = 'Zimbabwe';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Zimbabwe');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Zimbabwe');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Zimbabwé');
	-- Cities
	SELECT "ID" INTO _id FROM public."cl_Cities" WHERE "Name" = 'YDE';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Yaounde');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Yaounde');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Yaoundé');
	SELECT "ID" INTO _id FROM public."cl_Cities" WHERE "Name" = 'DLA';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Douala');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Douala');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Douala');
	SELECT "ID" INTO _id FROM public."cl_Cities" WHERE "Name" = 'MVR';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Maroua');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Maroua');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Maroua');
	SELECT "ID" INTO _id FROM public."cl_Cities" WHERE "Name" = 'GOU';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Garoua');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Garoua');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Garoua');
	SELECT "ID" INTO _id FROM public."cl_Cities" WHERE "Name" = 'NGE';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Ngaoundéré');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Ngaoundéré');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Ngaoundéré');
	SELECT "ID" INTO _id FROM public."cl_Cities" WHERE "Name" = 'EBA';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Ebolowa');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Ebolowa');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Ebolowa');
	SELECT "ID" INTO _id FROM public."cl_Cities" WHERE "Name" = 'BFM';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Bafoussam');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Bafoussam');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Bafoussam');
	SELECT "ID" INTO _id FROM public."cl_Cities" WHERE "Name" = 'BUA';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Buéa');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Buéa');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Buéa');
	SELECT "ID" INTO _id FROM public."cl_Cities" WHERE "Name" = 'BDA';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Bamenda');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Bamenda');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Bamenda');
	SELECT "ID" INTO _id FROM public."cl_Cities" WHERE "Name" = 'BTA';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Bertoua');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Bertoua');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Bertoua');
	SELECT "ID" INTO _id FROM public."cl_Cities" WHERE "Name" = 'BGF';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Bangui');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Bangui');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Bangui');
	SELECT "ID" INTO _id FROM public."cl_Cities" WHERE "Name" = 'BZV';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Brazzaville');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Brazzaville');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Brazzaville');
	SELECT "ID" INTO _id FROM public."cl_Cities" WHERE "Name" = 'LBV';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Libreville');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Libreville');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Libreville');
	SELECT "ID" INTO _id FROM public."cl_Cities" WHERE "Name" = 'SSG';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'Malabo');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'Malabo');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'Malabo');
	SELECT "ID" INTO _id FROM public."cl_Cities" WHERE "Name" = 'NDJ';
	CALL public."p_InsertLanguageRelation"(_us, _id, 'N''Djamena');
	CALL public."p_InsertLanguageRelation"(_gb, _id, 'N''Djamena');
	CALL public."p_InsertLanguageRelation"(_fr, _id, 'N''Djamena');
END $BODY$;