<?php

declare(strict_types=1);

namespace TS_Controller\Interfaces;

use TS_Http\Classes\Request;
use TS_Http\Classes\Response;

/**
 * Defines the contract for an action filter.
 * Filters can execute code before and after a controller action.
 */
interface IActionFilter
{
    /**
     * Called before the action method is executed.
     * Can be used for authorization, validation, or modifying the request.
     * If this method returns a Response object, the pipeline is short-circuited
     * and the action is never executed.
     *
     * @param Request $request The current request.
     * @param array $attributes The attributes found on the action method.
     * @return Response|null A response to stop execution, or null to continue.
     */
    public function onActionExecuting(Request $request, array $attributes): ?Response;

    /**
     * Called after the action method is executed.
     * Can be used for logging, modifying the response, or post-processing.
     *
     * @param Request $request The current request.
     * @param Response $response The response generated by the action.
     * @return Response The (potentially modified) response.
     */
    public function onActionExecuted(Request $request, Response $response): Response;
}